baseURL = 'https://example.org/'
languageCode = 'pt-pt'
title = 'Ritual do Habitual'
theme = 'shibui'

[params]
  author = "Andr√©"
  email = "your.email@example.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'